module.exports = [
  'transform',
  'transform-origin',
  'transform-style',
  'box-decoration-break',
  'backface-visibility',
  'perspective',
  'perspective-origin',
  'visibility',
  'opacity',
  'cursor',
  'filter',
  'isolation',
  'backdrop-filter',
  'mix-blend-mode',
]
